name: AmazonLinux2 Wheel Tester
on:
  push:
    branches:
      - master
  schedule:
    # Run nightly
    - cron: '0 0 * * *'

jobs:
  al2_wheel_test:
    runs-on: [self-hosted, linux, ARM64, c6g]
    container: amazonlinux:2
    strategy:
      fail-fast: false
      matrix:
        WHEEL:
          - PIP_NAME: numpy
            PKG_TEST: import numpy
          - PIP_NAME: bcrypt
            PKG_TEST: import bcrypt
          - PIP_NAME: pymongo
            PKG_TEST: |
              import pymongo
              import pymongo.message
          - PIP_NAME: lxml
            PKG_TEST: |
              import lxml._elementpath
              import lxml.builder
              import lxml.objectify
              import lxml.etree
              import lxml.sax
          - PIP_NAME: lazy-object-proxy
            PKG_TEST: import lazy_object_proxy
          - PIP_NAME: simplejson
            PKG_TEST: |
              import simplejson
              simplejson._speedups
          - PIP_NAME: Pillow
            PKG_TEST: |
              import PIL
              import PIL._imagingcms
              import PIL._imaging
              import PIL._imagingft
              import PIL._imagingmath
              import PIL._imagingmorph
          - PIP_NAME: kiwisolver
            PKG_TEST: import kiwisolver
          - PIP_NAME: cffi
            PKG_TEST: |
              import cffi
              ffi = cffi.FFI()
              a = ffi.new('int[4]')
              print(a)
          - PIP_NAME: cryptography
            PKG_TEST: |
              from cryptography.hazmat.backends.openssl.backend import backend
              print('Loaded: ' + backend.openssl_version_text())
              print('Linked Against: ' + backend._ffi.string(backend._lib.OPENSSL_VERSION_TEXT).decode('ascii'))
          - PIP_NAME: sqlalchemy
            PKG_TEST: import sqlalchemy
          - PIP_NAME: ujson
            PKG_TEST: import ujson
          - PIP_NAME: scikit-build cmake
            PKG_TEST: |
              import skbuild
              skbuild.cmaker.get_cmake_version()
          - PIP_NAME: pycryptodome
            PKG_TEST: import Crypto
          - PIP_NAME: pycryptodomex
            PKG_TEST: import Cryptodome
          - PIP_NAME: pandas
            PKG_TEST: import pandas
          - PIP_NAME: pywavelets
            PKG_TEST: import pywt
          - PIP_NAME: multidict
            PKG_TEST: import multidict
          - PIP_NAME: yarl
            PKG_TEST: import yarl
          - PIP_NAME: scipy
            PKG_TEST: import scipy
          - PIP_NAME: xgboost
            PKG_TEST: import xgboost
          - PIP_NAME: typed_ast
            PKG_TEST: import typed_ast
          - PIP_NAME: aiohttp
            PKG_TEST: import aiohttp
          - PIP_NAME: markupsafe
            PKG_TEST: import markupsafe
          - PIP_NAME: fastavro
            PKG_TEST: import fastavro
          - PIP_NAME: scikit-image
            PKG_TEST: import skimage
          # Test scikit image wheel for AL2 as it has 3.7 wheels, but not 3.8 for ubuntu
          - PIP_NAME: scikit-image==0.18.2rc2
            PKG_TEST: |
              from skimage import data, filters
              import numpy as np
              image = data.camera()
              thresholds = filters.threshold_multiotsu(image)
              regions = np.digitize(image, bins=thresholds)
          - PIP_NAME: scikit-learn
            PKG_TEST: import sklearn
          - PIP_NAME: statsmodels
            PKG_TEST: import statsmodels
          - PIP_NAME: gensim
            PKG_TEST: import gensim
          - PIP_NAME: cmake
            PKG_TEST: import cmake
          - PIP_NAME: protobuf
            PKG_TEST: import google.protobuf
          - PIP_NAME: Cython
            PKG_TEST: from Cython.Build import cythonize
          - PIP_NAME: pyspark
            PKG_TEST: import pyspark
          - PIP_NAME: opencv-python
            PKG_TEST: import cv2
          - PIP_NAME: gevent
            PKG_TEST: import gevent
          - PIP_NAME: pywavelets
            PKG_TEST: import pywt
          - PIP_NAME: torch
            PKG_TEST: import torch
          - PIP_NAME: torchvision
            PKG_TEST: import torchvision
          - PIP_NAME: grpcio
            PKG_TEST: import grpc
          - PIP_NAME: ninja
            PKG_TEST: import ninja
          - PIP_NAME: tensorflow
            PKG_TEST: import tensorflow
          - PIP_NAME: sentencepiece
            PKG_TEST: import sentencepiece
          - PIP_NAME: msgpack
            PKG_TEST: import msgpack
          - PIP_NAME: mypy
            PKG_TEST: from typing import Dict
          - PIP_NAME: Shapely
            PKG_TEST: from shapely.geometry import Point
          - PIP_NAME: ijson
            PKG_TEST: import ijson
          - PIP_NAME: snowflake-connector-python
            PKG_TEST: import snowflake.connector
          - PIP_NAME: lightgbm
            PKG_TEST: import lightgbm
          - PIP_NAME: twisted
            PKG_TEST: import twisted
          - PIP_NAME: tfx-bsl
            PKG_TEST: import tfx
          - PIP_NAME: pyarrow
            PKG_TEST: import pyarrow
          - PIP_NAME: h5py
            PKG_TEST: import h5py
          - PIP_NAME: tornado
            PKG_TEST: import tornado
          - PIP_NAME: pyzmq
            PKG_TEST: import zmq.backend
          #- PIP_NAME: psutil
          #  PKG_TEST: import psutil
          - PIP_NAME: matplotlib
            PKG_TEST: import matplotlib
          - PIP_NAME: psycopg2-binary
            PKG_TEST: import psycopg2
          - PIP_NAME: greenlet
            PKG_TEST: from greenlet import greenlet
          - PIP_NAME: regex
            PKG_TEST: import regex
          - PIP_NAME: websockets
            PKG_TEST: import websockets
          - PIP_NAME: docopt
            PKG_TEST: from docopt import docopt
          - PIP_NAME: absl-py
            PKG_TEST: |
              from absl import app
              from absl import flags
              from absl import logging
          - PIP_NAME: retrying
            PKG_TEST: from retrying import retry
          - PIP_NAME: pandocfilters
            PKG_TEST: from pandocfilters import toJSONFilter, Str
          - PIP_NAME: zope.interface
            PKG_TEST: from zope.interface import _zope_interface_coptimizations as c_opt
          #- PIP_NAME: grpc-google-iam-v1
          #  PKG_TEST: import google
          - PIP_NAME: ansible
            PKG_TEST: from ansible import context
          - PIP_NAME: thrift
            PKG_TEST: from thrift import Thrift
          #- PIP_NAME: mysqlclient
          #  PKG_TEST: import MySQLdb
          - PIP_NAME: apache-beam
            PKG_TEST: import apache_beam
          - PIP_NAME: tensorflow-data-validation
            PKG_TEST: import tensorflow_data_validation
          - PIP_NAME: pyyaml
            PKG_TEST: import yaml
          - PIP_NAME: future
            PKG_TEST: from __future__ import (division)
          - PIP_NAME: coverage
            PKG_TEST: import coverage
          - PIP_NAME: wrapt
            PKG_TEST: import wrapt
          - PIP_NAME: pyrsistent
            PKG_TEST: from pyrsistent import v, pvector
          - PIP_NAME: pynacl
            PKG_TEST: import nacl._sodium
          - PIP_NAME: dill
            PKG_TEST: import dill
          - PIP_NAME: nmslib
            PKG_TEST: import nmslib
          - PIP_NAME: pyproj
            PKG_TEST: import pyproj
          - PIP_NAME: lz4
            PKG_TEST: import lz4
          - PIP_NAME: setproctitle
            PKG_TEST: import setproctitle
          - PIP_NAME: google-crc32c
            PKG_TEST: import google_crc32c
          - PIP_NAME: jpype1
            PKG_TEST: import jpype
          - PIP_NAME: uvloop
            PKG_TEST: import uvloop
          - PIP_NAME: ddtrace
            PKG_TEST: import ddtrace
          - PIP_NAME: ruamel.yaml
            PKG_TEST: import ruamel.yaml
          - PIP_NAME: pyproj
            PKG_TEST: import pyproj
          - PIP_NAME: numexpr
            PKG_TEST: import numexpr
          - PIP_NAME: python-snappy
            PKG_TEST: import snappy
          - PIP_NAME: maturin
            PKG_TEST: import maturin
          - PIP_NAME: clickhouse-driver
            PKG_TEST: import clickhouse_driver
          - PIP_NAME: cmarkgfm
            PKG_TEST: import cmarkgfm
          - PIP_NAME: rapidfuzz
            PKG_TEST: import rapidfuzz
          - PIP_NAME: hiredis
            PKG_TEST: import hiredis
          - PIP_NAME: brotlicffi
            PKG_TEST: import brotlicffi
          - PIP_NAME: mecab-python3
            PKG_TEST: import MeCab
          - PIP_NAME: cassandra-driver
            PKG_TEST: import cassandra
          - PIP_NAME: confluent-kafka
            PKG_TEST: import confluent_kafka
          - PIP_NAME: coverage
            PKG_TEST: import coverage
          - PIP_NAME: netifaces
            PKG_TEST: import netifaces
          - PIP_NAME: scrypt
            PKG_TEST: import scrypt
          - PIP_NAME: grpcio-tools
            PKG_TEST: import grpc.tools
          - PIP_NAME: btrees
            PKG_TEST: from BTrees.OOBTree import OOBTree
          - PIP_NAME: pycares
            PKG_TEST: import pycares
          - PIP_NAME: advent-of-code
            PKG_TEST: import advent_of_code
          - PIP_NAME: biopython
            PKG_TEST: from Bio import SeqIO
          - PIP_NAME: pymupdf
            PKG_TEST: import fitz
    name: "Amazon Linux 2 for ${{ matrix.WHEEL.PIP_NAME }}"
    steps:
      - run: yum install -y python3-pip mesa-libGL
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install --no-cache-dir ${{ matrix.WHEEL.PIP_NAME }}
      - run: echo "${{ matrix.WHEEL.PKG_TEST }}" | python3